[tool.poetry]
name = "jinja2"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pip-tools = "^5.3.1"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
